force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>Product - {0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <formula>Opportunity__r.CloseDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <formula>Opportunity__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Product__c/Project_Product__c.object-meta.xml
<CustomObject>
    <label>Project Product</label>
    <nameField>
        <label>Project Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/Project_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Resources</relationshipLabel>
    <relationshipName>Projects_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectWrapperTest.cls
@isTest
public class ProjectWrapperTest {
    @isTest
   static void testGetProject() {
        // Create a test project
        Project__c testProject = new Project__c(Close_Date__c = Date.today(),
                                                Start_Date__c = Date.today().addDays(7));
        insert testProject;

        // Create a test project product
         Project_Product__c pp = new Project_Product__c(
        	Project__c = testProject.Id,
            Role__c = 'Developer',
            Quantity__c = 40
        );
        insert pp;


        // Create a test project resource
        Project_Resource__c testProjectResource = new Project_Resource__c(Project__c = testProject.Id, Resource__c = '005Dp000000OgubIAC',
                                                                            Start_Date__c = Date.today().addDays(2), 
                                                                            Close_Date__c = Date.today().addDays(5));
        

        Test.startTest();
        insert testProjectResource;
        // Call the getProject method with the test project's ID
        ProjectWrapper result = ProjectWrapper.getProject(testProject.Id);

        // Verify that the result object is not null and contains the correct data
        System.assertNotEquals(null, result);
        System.assertEquals(testProject.Id, result.project.Id);
        System.assertEquals(pp.Id, result.requirementList[0].projectProduct.Id);
        //System.assertEquals(testUser.Id, result.requirementList[0].users[0].Id);
        Test.stopTest();
    }

}