force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>Product - {0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Product__c/Project_Product__c.object-meta.xml
<CustomObject>
    <label>Project Product</label>
    <nameField>
        <label>Project Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/Project_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/fields/AssignedHours__c.field-meta.xml
<CustomField>
    <fullName>AssignedHours__c</fullName>
    <label>AssignedHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Resources</relationshipLabel>
    <relationshipName>Projects_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Project_Resource_Helper_Test.cls
@isTest
public class Project_Resource_Helper_Test {
	@isTest
    private static void testOne(){
        Project__c p = new Project__c();
        insert p;
        
        Project_Product__c pp = new Project_Product__c(
        	Project__c = p.Id,
            Role__c = 'Developer',
            Quantity__c = 40
        );
        insert pp;
        
       	Project_Resource__c pr = new Project_Resource__c(
        	Project__c = p.Id,
            Resource__c = '005Do000001SJJHIA4',
            AssignedHours__c = 20
        );
        insert pr;
        test.startTest();
          	pr.AssignedHours__c = 30;
          	update pr;
        test.stopTest();
        
        Project_Product__c testPP = [SELECT Id, Completed_Hours__c FROM Project_Product__c];
        System.assertEquals(30, testPP.Completed_Hours__c);
    }
    
    @isTest
    private static void testTwo(){
        Project__c p = new Project__c();
        insert p;
        
        Project_Product__c pp = new Project_Product__c(
        	Project__c = p.Id,
            Role__c = 'Developer',
            Quantity__c = 40
        );
        insert pp;
        
       	Project_Resource__c pr = new Project_Resource__c(
        	Project__c = p.Id,
            Resource__c = '005Do000001SJJHIA4',
            AssignedHours__c = 20
        );
        insert pr;
        test.startTest();
          	delete pr;
        test.stopTest();
        
        Project_Product__c testPP = [SELECT Id, Completed_Hours__c FROM Project_Product__c];
        System.assertEquals(0, testPP.Completed_Hours__c);
    }
}