force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>Product - {0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Opportunity__r.Amount</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <formula>Opportunity__r.CloseDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <formula>Opportunity__r.Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Product__c/Project_Product__c.object-meta.xml
<CustomObject>
    <label>Project Product</label>
    <nameField>
        <label>Project Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/Project_Resource__c.object-meta.xml
<CustomObject>
    <label>Project Resource</label>
    <nameField>
        <label>Project Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Resource__c/fields/AssignedHours__c.field-meta.xml
<CustomField>
    <fullName>AssignedHours__c</fullName>
    <label>AssignedHours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_Resource__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Projects Resources</relationshipLabel>
    <relationshipName>Projects_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectWrapper.cls
public class ProjectWrapper {
    
    @auraEnabled
    public Project__c Project;
    @auraEnabled
    public List<Project_Resource__c> ProjectResources; //Set<Id> ProjectResources;?
    @auraEnabled
    public List<Project_Product__c> ProjectProducts; //Set<Id> ProjectProducts;?
    @auraEnabled
    public List<User> Resources; //Set<Id> Resources;?
    
    public ProjectWrapper (Project__c Project, List<Project_Resource__c> ProjectResources, List<Project_Product__c> ProjectProducts, List<User> Resources){
        this.project = project;
        this.ProjectProducts = ProjectProducts;
        this.ProjectResources = ProjectResources;
        this.Resources = Resources;
    }      	 


    @AuraEnabled(cacheable=true)
    public static ProjectWrapper getProject (Id projectId) {
        List<Project_Product__c> ProjectProducts = [SELECT Id, Project__c, Quantity__c, Amount__c, Role__c, Completed_Hours__c 
													FROM Project_Product__c 
                                                    WHERE Project__c = :projectId];
        
        List<Project_Resource__c> ProjectResources = [SELECT Id, Project__c, Resource__c, Start_Date__c, Close_Date__c, Role__c, AssignedHours__c, Is_Squad_Lead__c 
                                                     FROM Project_Resource__c 
                                                     WHERE Project__c = :projectId];
        
       /* List<Id> ResourcesIds = new List<Id>();
        
            for(Project_Resource__c PR: ProjectResources){
				ResourcesIds.add(PR.Resource__c);                
            }*/
        List<String> rolAvailable = new List<String>{'Developer','Architect','Consultant', 'Project Manager'};
        
        List<UserRole> roles = [SELECT Id, Name FROM UserRole WHERE Name in :rolAvailable];
        	
        List<User> Resources = [SELECT Id, Rate__c, UserRoleId FROM User WHERE UserRoleId in :roles];
        
        Project__c project = [SELECT Id, Name, Amount__c, Client__c, Close_Date__c, Start_Date__c
 							FROM Project__c WHERE Id = :projectId];
        
        ProjectWrapper pr2 = new ProjectWrapper(Project, ProjectResources, ProjectProducts, Resources);

        return pr2;
    }
}